language: csharp 
solution: Gravity/Gravity.sln
dist: trusty
mono: none
dotnet: 2.1
branches:  
  only:  
    - master
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - ./build.sh
