language: csharp 
solution: Gravity/Gravity.sln
dist: trusty
mono: latest
dotnet: 2.1
branches:  
  only:  
    - master
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore Gravity/Gravity.sln
  - mono nuget.exe install xunit.runner.console -Version 2.4.1  -OutputDirectory testrunner
script:
  - ./build.sh
