language: csharp 
solution: Gravity/Gravity.sln
dist: trusty
mono: none
dotnet: 2.1
branches:  
  only:  
    - master
install:
  - nuget restore Gravity/Gravity.sln -Verbosity detailed
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Gravity/Gravity.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./Gravity/Geotechnic.Domain.Tests.Unit/bin/Release/netcoreapp2.1/Geotechnic.Domain.Tests.Unit.dll.dll
